### ISSUE TITLE
Can't save renewed personal Github token.

### ISSUE THREAD

**Issue by marchingon12** [brumm/tako#37] opened 2020-10-04 23:06 UTC
After experiencing this a few times:
![image](https://user-images.githubusercontent.com/41235480/95029228-3f317900-0696-11eb-989b-7d31ab3de2c4.png)

I reinstalled Tako. But when I tried saving the renewed personal token (regenerating token within Personal Access Tokens github settings), the save button is greyed out for some reason. 
![image](https://user-images.githubusercontent.com/41235480/95029314-d1398180-0696-11eb-85f2-1f941e768d50.png)

![image](https://user-images.githubusercontent.com/41235480/95029178-f2e63900-0695-11eb-99bb-3d24200d79f0.png)

**Comment by brumm** [comment] 2020-10-13 08:50
Thanks for letting me know! I'll try to recreate this case. In the meantime: The button should only be disabled if your token does not pass this regex: `/[\da-f]{40}/.test(token)` can you make sure that it does? Use this link and paste your token in the box below the regex string: https://regex101.com/r/Ai9N16/1 The entire token string should be highlighted in blue.

**Comment by brumm** [comment] 2020-12-09 08:47
I'll close this for now, because it's not actionable for me. Feel free to comment with more info or a reproduction case

**Closed as completed by brumm** 2020-12-09 08:47 UTC
